### ISSUE TITLE
3.9.2 breaks pipenv?

### ISSUE THREAD

**Issue by Matt-Eva** [learn-co-curriculum/python-p3-environment-setup#1]
### Canvas Link

https://learning.flatironschool.com/courses/6049/pages/environment-setup?module_item_id=467997

### Concern

When I set my global version of python to 3.9.2 using pyenv as per the instructions, I was no longer able to use pipenv. Once I switched back to 3.8.13 (using pyenv), I was able to use pipenv again. I'm not sure if other people have already experienced this, but we should tell students to set their global version to a version of python that pipenv can work with.

**Comment by professor-ben** [comment]
Thanks for raising this issue, Matt. This might indicate something we need to change with the environment setup documentation. For now, I'm going to kick this Prabhdip's way and see if he can square this circle.

**Comment by pgill3** [comment]
Hi @Matt-Eva ,
 can you send me what the error the terminal returns when you try to install? 

I have an suspicion it is this 
`ERROR:: --system is intended to be used for pre-existing Pipfile installation, not installation of specific packages. Aborting.` 

If so running the `pipenv --rm` command should get rid of the previous virtual environment. Then you will be able to `pipenv` commands again.

I will make changes to the README but can you try that or send me the terminal output just so I can be sure.

**Comment by Matt-Eva** [comment]
Hey Prabhdip! Yeah, I can't remember the exact circumstances under which this issue originally arose, but when I try to run `pipenv` while using `3.9.2` globally, I get this error:

```
pyenv: pipenv: command not found

The `pipenv' command exists in these Python versions:
  3.8.13

Note: See 'pyenv help global' for tips on allowing both
      python2 and python3 to be found.
```
