### ISSUE TITLE
Tell students to code along?

### ISSUE THREAD

**Issue by Matt-Eva** [learn-co-curriculum/python-p3-environment-setup#2]
### Canvas Link

https://learning.flatironschool.com/courses/6049/pages/environment-setup?module_item_id=467997

### Concern

We ask students to run commands in their terminal, then notice changes in 'the directory'. We might want to specify that students should fork and clone this lab, so they know where to look. I can see students running these commands in their terminal without forking and cloning, then becoming confused as to where they should look.

**Comment by linda-seiter** [comment]
#7
