### ISSUE TITLE
Tell students to switch global back to 3.8.13?

### ISSUE THREAD

**Issue by Matt-Eva** [learn-co-curriculum/python-p3-environment-setup#6]
### Canvas Link

https://my.learn.co/courses/653/pages/environment-setup?module_item_id=83719

### Concern

In this lesson, we tell students to install `3.9.2` and then set it as the global Python version. We then also ask them to re-install `pipenv`, which they should have already done earlier.

We then tell them to run a command using `3.8.13`, which seems to be causing confusion for students and occasionally results in environment issues.

Why are we having students do this? To just have them practice managing different Python versions? Why don't we tell students to reset the global version to `3.8.13`, as that's the version that's used throughout the course? (According to my knowledge.)

I'm happy to open up a PR that resolves these issues / ambiguities, but I don't know what I should be adding at present - this lesson is just too vague and confusing with its purpose, intent, and direction.

**Comment by linda-seiter** [comment]
fixed #7
